[12.0][IMP] partner_risk_insurance: Add tracking to company_credit_limit and insurance_credit_limit on partners
OCA/credit-control pull request #118
Opened 2021-02-04 15:36 UTC by CarlosRoca13

cc @Tecnativa TT28073

please @sergio-teruel @carlosdauden  review this

2021-02-04 18:09 UTC, marcelsavegnago approved these changes

2021-02-04 20:18 UTC, Tardo requested changes

2021-02-04 20:18 UTC, Tardo commented on partner_risk_insurance/models/res_partner.py
> +        tracking=True,
You mean 'track_visibility'?

2021-02-04 20:18 UTC, Tardo commented on partner_risk_insurance/models/res_partner.py
> +        tracking=True,
You mean 'track_visibility'?

2021-02-05 08:20 UTC, CarlosRoca13 commented
@Tardo yes, was a confusion

2021-02-05 11:27 UTC, Tardo approved these changes

2021-02-05 17:50 UTC, pedrobaeza commented
/ocabot merge patch

2021-02-05 19:46 UTC, merged