[13.0][FIX] account_financial_risk: Show ValidationError when post multiple invoices…
OCA/credit-control pull request #148
Opened 2021-09-03 08:19 UTC by carlosdauden

… from wizard. Avoid singleton with multi-company _autopost_draft_entries.
 When we post from validate.account.move wizard, validate_move returns 'ir.actions.act_window_close'.
 Fixed issue #147 

@Tecnativa TT30969

2021-09-03 18:07 UTC, pedrobaeza commented
Can you please check Travis?

2021-09-06 11:34 UTC, pedrobaeza approved these changes

2021-09-06 11:37 UTC, pedrobaeza requested changes

2021-09-06 11:37 UTC, pedrobaeza commented on account_financial_risk/tests/test_account_financial_risk.py
> +        wiz_dic = invoice_form.post()
This is a `Form` and can't run methods. I think the problem is that you are posting twice, so the solution is:

```suggestion
```

2021-09-06 14:32 UTC, carlosdauden commented
Tests fixed

2021-09-24 11:55 UTC, pedrobaeza approved these changes

2021-09-24 11:55 UTC, pedrobaeza commented
/ocabot merge patch

2021-09-24 12:14 UTC, merged