[15.0][MIG] account_credit_control: Migration to 15.0
OCA/credit-control pull request #192
Opened 2022-06-13 00:42 UTC by cesar-tecnativa

TT36416

2022-06-14 06:50 UTC, pedrobaeza commented
Please check CI

2022-07-04 08:30 UTC, BT-aestebanez approved these changes
LGTM

2022-07-04 16:42 UTC, pedrobaeza commented
CI is still red, @cesar-tecnativa

2022-07-04 22:18 UTC, cesar-tecnativa commented
TT36416

2022-07-04 22:18 UTC, cesar-tecnativa commented
@pedrobaeza Could you please review?

2022-07-04 22:18 UTC, cesar-tecnativa commented
@victoralmau could you please review?

2022-07-05 05:23 UTC, cesar-tecnativa commented
@LudLaf could you review this?

2022-07-05 09:50 UTC, BT-anieto requested changes

2022-07-05 09:50 UTC, BT-anieto commented on account_credit_control/views/res_config_settings_view.xml
> +                            />
Not existing! This code should not be here.

2022-07-05 09:53 UTC, BT-anieto commented
@cesar-tecnativa credit_control_policy field is not existing. How it is right now it breaks the update.

2022-07-05 09:55 UTC, BT-anieto commented on account_credit_control/views/res_config_settings_view.xml
> +                                for="default_control_tolerance"
I guess here as well

2022-07-05 10:07 UTC, BT-anieto commented
On the other hand, I guess the migrations folder should be deleted.

2022-07-05 11:45 UTC, BT-anieto commented on account_credit_control/models/mail_message.py
> +        credit_control = self.env["ir.model.data"].xmlid_to_res_id(
In the core it has been renamed to **_xmlid_to_res_id**

2022-07-06 09:11 UTC, BT-anieto approved these changes
LGTM

2022-07-06 09:11 UTC, BT-anieto commented on account_credit_control/views/res_config_settings_view.xml
> +                          </div>
Not clean formated but it was like that in previous version.

2022-07-06 09:11 UTC, BT-anieto commented on account_credit_control/views/res_config_settings_view.xml
> +                        </div>
Not clean formated but it was like that in previous version.

2022-07-06 19:49 UTC, cesar-tecnativa commented
@CarlosRoca13 please review

2022-07-07 05:30 UTC, CarlosRoca13 approved these changes

2022-07-07 09:49 UTC, espo-tony approved these changes

2022-07-13 16:35 UTC, LudLaf commented
> On the other hand, I guess the migrations folder should be deleted.

Migrations folder now deleted.

2022-07-14 00:07 UTC, cesar-tecnativa commented
@pedrobaeza Could you please review?

2022-07-24 10:32 UTC, pedrobaeza commented
/ocabot merge nobump

2022-07-24 10:32 UTC, pedrobaeza commented
/ocabot migration account_credit_control

2022-07-24 10:38 UTC, merged