[MIG] partner_financial_risk: Migration to 11.0
OCA/credit-control pull request #2
Opened 2018-05-07 19:39 UTC by carlosdauden

@Tecnativa

2018-05-08 09:03 UTC, chienandalu reviewed
Runbot is failing (502 Bad Gateway)

2018-05-14 19:11 UTC, pedrobaeza approved these changes
I'm not sure why runbot is not building a working instance, but I have tried it locally.

2018-06-12 16:16 UTC, sergio-teruel requested changes

2018-06-12 16:16 UTC, sergio-teruel commented on account_financial_risk/__init__.py
> +from . import wizard
Use plural form 
[https://github.com/OCA/maintainer-tools/tree/master/template/module](url)

2018-06-12 16:16 UTC, sergio-teruel commented on account_financial_risk/data/account_financial_risk_data.xml
> +    <!--<field name="doall" eval="False"/>-->
Remove if not used

2018-06-12 16:16 UTC, sergio-teruel commented on account_financial_risk/views/res_config_view.xml
> +        <xpath expr=".//div[@id='account_followup']/.." position="inside">
Remove dot.

2018-06-12 16:16 UTC, sergio-teruel commented on account_financial_risk/views/res_config_view.xml
> +                        <div class="row mt16" title="">
Empty title attribute?

2018-06-12 16:16 UTC, sergio-teruel commented on account_financial_risk/views/res_partner_view.xml
> +
Remove blank line

2018-06-12 16:16 UTC, sergio-teruel commented on account_financial_risk/views/res_partner_view.xml
> +                <page name="financial_risk" string="Financial Risk" attrs="{'invisible': [('customer','=',False)]}">
Add white spaces in the domain

2018-06-13 14:30 UTC, oihane approved these changes
Technically reviewed

2018-06-13 14:32 UTC, pedrobaeza commented
@carlosdauden can you attend the remaining comments?

2018-06-13 15:42 UTC, carlosdauden commented
@sergio-teruel Changes attended

2018-06-13 16:03 UTC, rafaelbn commented
@carlosdauden travis is :red_circle: just missing travis! :+1:

2018-06-20 22:11 UTC, pedrobaeza commented
@moylop260 do you have any clue why Travis is failing in this 11.0 branch due to absence of PyPDF2 library? https://travis-ci.com/OCA/credit-control/jobs/130482431#L600

2018-06-20 22:31 UTC, pedrobaeza commented
@moylop260 I see that the .travis.yml is not correct. Fixing it.

2018-06-20 22:55 UTC, pedrobaeza commented
Finally green! Merging

2018-06-20 22:55 UTC, merged