[15.0][IMP] account_financial_risk: credit limit last modification date field.
OCA/credit-control pull request #227
Opened 2022-10-31 13:02 UTC by angelgarciadelachica

A new field is created that stores the date of the last credit limit modification if the credit limit is non-zero.
In case the credit limit is non-zero, the date of the last modification is displayed next to the credit limit in the customer's Finacial Risk tab.
![Captura 01](https://user-images.githubusercontent.com/101106685/199014005-85ccf8c2-e551-484b-bfe7-d177b4a199f5.png)

2022-10-31 13:03 UTC, angelgarciadelachica commented
@ValentinVinagre @HaraldPanten

2022-10-31 13:06 UTC, pedrobaeza commented
The field is already tracked:

https://github.com/OCA/credit-control/blob/9e5ecdfa93ab2d8207792d70b979d6aef5c5f5dc/account_financial_risk/models/res_partner.py#L132

and thus, each change is written on the chatter with the date, so you have the full change history.

I think that adding overhead for the same feature doesn't worth.

2022-10-31 13:18 UTC, ValentinVinagre commented
> The field is already tracked:
> 
> https://github.com/OCA/credit-control/blob/9e5ecdfa93ab2d8207792d70b979d6aef5c5f5dc/account_financial_risk/models/res_partner.py#L132
> 
> and thus, each change is written on the chatter with the date, so you have the full change history.
> 
> I think that adding overhead for the same feature doesn't worth.

It is true that there is a tacking, but when you try to filter those that indicated the credit limit for more than 6 months or 1 year to request it again, you cannot see that information. In this way if it would be possible and it is hidden next to the maximum.

2022-10-31 13:20 UTC, pedrobaeza commented
I don't see that a great problem, but if others think that the overhead is worth, then go ahead.

2022-11-02 08:16 UTC, ValentinVinagre approved these changes
LGTM 👍🏻

2022-11-02 08:16 UTC, ValentinVinagre commented
@HaraldPanten could you check it?

2022-11-02 08:29 UTC, carlosdauden requested changes

2022-11-02 08:29 UTC, carlosdauden commented on account_financial_risk/models/res_partner.py
> +        readonly=True,
Maybe this field should be writable. (keeping the rest of the functionality)
What happens if we want to save the date in which we have changed the conditions and that date has already passed?
In Spain, it is quite common for the administration department to introduce the modifications with some delay. :wink: 
```suggestion
        readonly=False,
```

2022-11-02 08:29 UTC, carlosdauden commented on account_financial_risk/models/res_partner.py
> +        )
```suggestion
        self.filtered(lambda x: x.credit_limit == 0.00).date_credit_limit = False
```

2022-11-02 08:29 UTC, carlosdauden commented on account_financial_risk/models/res_partner.py
> +        )
```suggestion
        self.filtered(lambda x: x.credit_limit != 0.00).date_credit_limit = datetime.today()
```

2022-11-03 08:12 UTC, HaraldPanten commented
@angelgarciadelachica once you check Carlos's comments, that will be OK for me.

2022-11-03 11:45 UTC, carlosdauden approved these changes
Code LGTM

2022-11-03 12:49 UTC, pedrobaeza commented
The repo needs a copier template update. Can you please do it here or in a separate PR?

2022-11-03 15:39 UTC, HaraldPanten commented
Hi @pedrobaeza is that the same as your team did here, right? --> https://github.com/OCA/l10n-spain/pull/2579

2022-11-03 15:40 UTC, pedrobaeza commented
Yes, it's executing `copier -f update` in the repo.

2022-11-03 15:41 UTC, HaraldPanten commented
THX! we'll have a look 👍

2022-11-04 09:23 UTC, HaraldPanten approved these changes

2022-11-04 09:40 UTC, angelgarciadelachica commented
It's done!
THX @pedrobaeza.
In case someone has the same problem I found the following link to fix it:
https://github.com/OCA/oca-addons-repo-template

2022-11-04 10:24 UTC, pedrobaeza commented
/ocabot merge minor

2022-11-04 10:36 UTC, merged

2022-11-04 13:14 UTC, carlosdauden commented
Can you review this view in edition mode?

![image](https://user-images.githubusercontent.com/7701001/199981009-3f908299-185a-4d81-a952-7036f651bcf0.png)

2022-11-07 09:05 UTC, angelgarciadelachica commented
Sure, I check it.