[BUG] Technical contradiction solved
OCA/credit-control pull request #229
Opened 2022-11-08 10:52 UTC by PeterSchwarzHPI

As the self.ensure_one() is meant to ensure that a function can only be applied on exactly one record of a recordset and the function "check_warnings" still iterates over all records (not returning anything but really just checking) it doesn't make sense to keep this piece of code.
Additionally it causes issues when trying to work on multiple records.

2022-11-11 12:15 UTC, AaronHForgeFlow reviewed
Makes sense. Can you fix-precommit? Not sure if a rebase is needed

2022-11-11 13:48 UTC, PeterSchwarzHPI commented
It's actually the newest version of the repository (my fork is 1 commit ahead).
Additionally it just says, that a Python library is not importable so I assume it's Python 3.11. issue.

2022-11-14 11:31 UTC, carlosdauden approved these changes
Fix pre-commit.

2022-11-14 11:38 UTC, PeterSchwarzHPI commented
@carlosdauden is that supposed to be a request or did you somehow fixed the pre-commit issue?

As I already pointed out there is nothing to fix from my side because it seems to be an issue with the framework running those pre-commits.

If you check out the error message you will see that it's not due to my changes. As I said my fork is one commit ahead.

2022-11-14 12:14 UTC, carlosdauden commented
Ok, I thought it would be solved with rebase.

2022-11-14 15:18 UTC, pedrobaeza approved these changes

2022-11-14 15:31 UTC, pedrobaeza commented
Pre-commit has been fixed in #231.

Please rebase now and change the commit message to `[FIX] account_invoice_overdue_reminder: No ensure_one in check_warnings` following the commit message guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

2022-11-15 07:04 UTC, PeterSchwarzHPI commented
Done.

2022-11-15 07:08 UTC, pedrobaeza requested changes
You have mangled the commit history. You have to rebase, not to pull.

2022-11-15 07:35 UTC, PeterSchwarzHPI commented
You're absolutely right. Fixed that.

2022-11-15 07:36 UTC, pedrobaeza approved these changes

2022-11-15 07:36 UTC, pedrobaeza commented
/ocabot merge patch

2022-11-15 07:40 UTC, merged