[12.0] [ADD] Credit control analysis
OCA/credit-control pull request #24
Opened 2019-07-25 13:18 UTC by qgroulard

Add a SQL view which summarizes level reached and open balance per partner, policy and currency.
Useful for reporting based on level reached by customers (also displayed in partner form view).

2019-07-25 13:40 UTC, pedrobaeza commented
Why new module? I think this can fit perfectly in existing module, as it doesn't require anything extra and it's not something that is changing behavior.

2019-07-25 16:01 UTC, sbidoul commented on account_credit_control/models/res_partner.py
> +    )
This field should either go to credit_control_analysis, or as @pedrobaeza suggests, merge the two modules. Merging them is fine with me.

2019-07-25 16:01 UTC, sbidoul commented on account_credit_control/report/account_credit_control_analysis.py
> +                    THEN sum(amount_residual_currency)
@qgroulard as you proposed, remove amount_residual_currency, it does not make sense.

2019-07-25 16:01 UTC, sbidoul commented on account_credit_control/report/account_credit_control_analysis.py
> +    open_balance = fields.Float(string="Open Balance", readonly=True)
Can you add a help text explaining more precisely what this open balance is (eg saying it is the open balance on credit control lines of the same policy).

2019-07-30 08:16 UTC, sbidoul approved these changes
Looks good (code review)

2019-09-30 13:22 UTC, houssine78 approved these changes
LGTM

2019-09-30 13:24 UTC, houssine78 commented
version increment needed

2019-09-30 13:32 UTC, astirpe requested changes

2019-09-30 13:32 UTC, astirpe commented on account_credit_control/models/credit_control_line.py
> +        readonly=True,
No need of `readonly=True,` since it's the default behavior for a related field in 12.0.

```suggestion
```

2019-09-30 13:32 UTC, astirpe commented on account_credit_control/report/account_credit_control_analysis.py
> +        comodel_name="res.partner", string="Partner", readonly=True
No need of string="...", since odoo automatically does the job.

```suggestion
        comodel_name="res.partner", readonly=True
```

2019-09-30 13:32 UTC, astirpe commented on account_credit_control/report/account_credit_control_analysis.py
> +        comodel_name="res.currency", string="Currency", readonly=True
No need of string="...", since odoo automatically does the job.

```suggestion
        comodel_name="res.currency", readonly=True
```

2019-09-30 13:32 UTC, astirpe commented on account_credit_control/report/account_credit_control_analysis.py
> +        string="Open Balance",
No need of string="...", since odoo automatically does the job.

```suggestion
```

2019-10-01 09:51 UTC, astirpe approved these changes

2019-10-04 13:52 UTC, houssine78 approved these changes

2019-10-04 14:21 UTC, sbidoul commented on setup/account_credit_control_analysis/setup.py
> +)
@qgroulard these setup.py now refers to an non-existent module. Can you remove it?

After that we can merge.

2019-10-17 16:42 UTC, qgroulard commented
@OCA/core-maintainers , This PR is ready to merge

2019-10-17 17:04 UTC, sbidoul commented
/ocabot merge minor

2019-10-17 17:17 UTC, merged