[FIX] account_financial_risk - adapt exception msg to multi company
OCA/credit-control pull request #243
Opened 2023-01-16 09:54 UTC by baimont

Running the account's cron "Account; Post draft entries with auto_post set to True up to today" on a multi companies database, we got an Expected singleton error:

`ValueError: <class 'ValueError'>: "Expected singleton: res.company(1, 2)" while evaluating 'model._autopost_draft_entries()'`

that we traced back to this line.

2023-01-16 10:02 UTC, carlosdauden requested changes

2023-01-16 10:02 UTC, carlosdauden commented on account_financial_risk/models/account_invoice.py
>          for invoice in self.filtered(lambda x: x.move_type == "out_invoice"):
Try don't repeat loop
```suggestion
        if self.env.context.get("bypass_risk", False):
            return ret
        for invoice in self.filtered(lambda x: x.move_type == "out_invoice" and not x.company_id.allow_overrisk_invoice_validation):
```

2023-01-16 10:27 UTC, carlosdauden approved these changes

2023-01-16 11:00 UTC, FrancoMaxime approved these changes

2023-01-19 09:54 UTC, acsonefho approved these changes
LGTM

2023-01-19 09:55 UTC, acsonefho commented
@OCA/accounting-maintainers if someone have super-power here to review/merge here!
Easy one!

2023-01-19 10:43 UTC, AaronHForgeFlow approved these changes

2023-01-19 10:44 UTC, AaronHForgeFlow commented
/ocabot merge patch

2023-01-19 10:44 UTC, AaronHForgeFlow commented
@baimont thanks for the fix. Can you check if it is needed in v15?

2023-01-19 10:47 UTC, merged

2023-01-20 19:12 UTC, pedrobaeza commented
Can you fw-port this to upper versions?

2023-02-08 11:22 UTC, pedrobaeza commented
Please someone do the forward-port

2023-08-14 05:55 UTC, pedrobaeza commented
Forward-ported on #303