[16.0][MIG] account_credit_control
OCA/credit-control pull request #268
Opened 2023-02-28 15:13 UTC by astirpe

Continue from https://github.com/OCA/credit-control/pull/242

2023-03-06 18:16 UTC, Bearnard21 requested changes
There's an error when you try to get into the partner (no matter if it's a customer or vendor).
The error code:

`Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1613, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1810, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 149, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 457, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 430, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 1605, in name_search
    ids = self._name_search(name, args, operator, limit=limit)
  File "/opt/odoo/odoo/models.py", line 1624, in _name_search
    return self._search(args, limit=limit, access_rights_uid=name_get_uid)
  File "/opt/odoo/odoo/models.py", line 4624, in _search
    query = self._where_calc(domain)
  File "/opt/odoo/odoo/models.py", line 4392, in _where_calc
    return expression.expression(domain, self).query
  File "/opt/odoo/odoo/osv/expression.py", line 447, in __init__
    self.parse()
  File "/opt/odoo/odoo/osv/expression.py", line 849, in parse
    ids2 = comodel._name_search(right, domain or [], op2, limit=None)
  File "/opt/odoo/addons/account/models/account_account.py", line 580, in _name_search
    return self._search(expression.AND([domain, args]), limit=limit, access_rights_uid=name_get_uid)
  File "/opt/odoo/odoo/models.py", line 4624, in _search
    query = self._where_calc(domain)
  File "/opt/odoo/odoo/models.py", line 4392, in _where_calc
    return expression.expression(domain, self).query
  File "/opt/odoo/odoo/osv/expression.py", line 447, in __init__
    self.parse()
  File "/opt/odoo/odoo/osv/expression.py", line 1024, in parse
    expr, params = self.__leaf_to_sql(leaf, model, alias)
  File "/opt/odoo/odoo/osv/expression.py", line 1100, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term ('name', 'in', 'property_account_receivable_id')

The above server error caused the following client error:
null`

2023-03-07 07:52 UTC, astirpe commented
Thank you @Bearnard21, should be fixed now

2023-03-07 09:28 UTC, astirpe commented
Thank you @Bearnard21, should be working now

2023-03-24 05:06 UTC, nguyenminhchien reviewed
Hi @astirpe, i just added some comments, feel free to discuss with me bout them.
Thank you,

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/README.rst
> +company form.
@astirpe cannot find "`Accounting tab`" but "`General Information`"
![image](https://user-images.githubusercontent.com/8724793/227418568-4bd3e47c-cfba-4db6-ab89-93bc173ea000.png)

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/README.rst
> +Menu entries are located in *Invoicing > Adviser > Credit Control*.
@astirpe cannot find the menu `Invoicing > Adviser > Credit Control` but `Invoicing > Credit Control`

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_line.xml
> +            </tree>
There are too many fields shown on the tree view, could we hide some (by adding the optional="hide"), such as move_line_id,  account_id, amount_due,..  ? 
(If a user want to see all fields, he can open the form view instead)
![image](https://user-images.githubusercontent.com/8724793/227419553-b0f1648d-02f8-4581-b9a8-a74ac95e87d6.png)

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_line.xml
> +                <field name="currency_id" />
If you want to show `currency_id`, you should add `groups="base.group_multi_currency"`.
But you should hide it, show `amount_due`, `balance_due` by using `widget="monetary"`

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_communication.xml
> +                            <field name="currency_id" />
If you want to show `currency_id`, you should add `groups="base.group_multi_currency".`
But you should hide it, show `total_invoiced`, `total_due` by using `widget="monetary"
`

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_communication.xml
> +                            <field name="company_id" />
You should add `groups="base.group_multi_company" `

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_communication.xml
> +                    <field name="company_id" />
You should add `groups="base.group_multi_company" `

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_communication.xml
> +                        string="Company"
You should add `groups="base.group_multi_company" `

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_communication.xml
> +                <field name="company_id" />
You should add `groups="base.group_multi_company" `

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_line.xml
> +                            <field name="currency_id" />
If you want to show `currency_id`, you should add `groups="base.group_multi_currency"`.
But you should hide it, show `amount_due`, `balance_due` by using `widget="monetary"`

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_policy.xml
> +                    <field name="company_id" />
You should add `groups="base.group_multi_company" `

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/credit_control_policy.xml
> +                    <field name="active" />
There is already a field for `active` at line 17

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/views/res_partner.xml
> +                        >
![image](https://user-images.githubusercontent.com/8724793/227422318-b8c9bf14-48a0-4ac5-a230-246ea9dca246.png)
Can we add more space between `payment_next_action_date` and `credit_control_analysis_ids` ?
It confused me at the first look, because i thought `Next Action Date?` was the label of the table below

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/models/account_move.py
> +            cc_draft_line.unlink()
We should search nondraft, ad draft line of all invoices at the same time (no need to loop  `for invoice in self`)
replace the domains
> nondraft_domain = [("invoice_id", "=", invoice.id),("state", "!=", "draft")]
> draft_domain = [("invoice_id", "=", invoice.id), ("state", "=", "draft")]

By
> nondraft_domain = [("invoice_id", "in", invoice.ids),("state", "!=", "draft")]
> draft_domain = [("invoice_id", "in", invoice.ids), ("state", "=", "draft")]

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/models/account_move.py
> +            cc_nondraft_lines = cc_line_obj.search(nondraft_domain)
Add `limit=1`

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/models/credit_control_communication.py
> +        table_content += "</table>"
Why don't we handle the `table_content` in the mail template? it's easier for the user when updating the table format

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/models/credit_control_policy.py
> +        lines = (lines | to_add) - to_remove
Because all invoice lines must be for a particular company. I cannot find the case where `(lines | to_add)`  != `lines`.
I mean that we don't need `to_add` in both cases `_get_partner_related_lines` and `_get_invoice_related_lines`.

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/security/acl_account_credit_control_analysis.xml
> +    </record>
why don't add this access right in `ir.model.access.csv`

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/security/acl_res_partner_payment_action_type.xml
> +</odoo>
why don't add these access rights in `ir.model.access.csv`

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/wizard/credit_control_policy_changer_view.xml
> +        id="action_wizard_credit_policy_changer_menu_action"
this action just opens a blank form
![image](https://user-images.githubusercontent.com/8724793/227428578-2aa24d9b-f182-471a-b613-3362f5a2fbc7.png)

2023-03-24 05:06 UTC, nguyenminhchien commented on account_credit_control/wizard/credit_control_policy_changer_view.xml
> +    <record id="action_wizard_credit_policy_changer" model="ir.actions.act_window">
cannot find a menu call this action

2023-03-27 14:28 UTC, astirpe commented on account_credit_control/models/credit_control_communication.py
> +        table_content += "</table>"
@nguyenminhchien than you for your review!

This part was probably implemented this way for a reason. I would not change this part since this PR was meant to be a pure module migration. We can later on create a separate PR dedicated to code refactoring, what do you think?

2023-03-27 14:30 UTC, astirpe commented on account_credit_control/models/credit_control_policy.py
> +        lines = (lines | to_add) - to_remove
I tend to agree with you, but I don't know why this part was implemented this way. Maybe to allow `_get_partner_related_lines` and `_get_invoice_related_lines` to be extended by extra modules?

2023-03-27 14:32 UTC, astirpe commented on account_credit_control/wizard/credit_control_policy_changer_view.xml
> +        id="action_wizard_credit_policy_changer_menu_action"
I see. I'm trying to understand what was the original behavior of this wizard. Do you maybe know what part should I fix?

2023-03-27 14:34 UTC, astirpe commented on account_credit_control/wizard/credit_control_policy_changer_view.xml
> +    <record id="action_wizard_credit_policy_changer" model="ir.actions.act_window">
Me neither, I'm trying to understand how was this originally supposed to work

2023-03-30 03:26 UTC, nguyenminhchien commented on account_credit_control/models/credit_control_communication.py
> +        table_content += "</table>"
Ok for me to keep it as is (because it still works). But it's better if you could make the source code looks more perfect.

2023-03-30 03:32 UTC, nguyenminhchien commented on account_credit_control/models/credit_control_policy.py
> +        lines = (lines | to_add) - to_remove
Yes, maybe. So, just let `to_add = self.env["account.move.line"]` in `def _move_lines_subset()`
Extended modules will update it then

2023-03-30 03:44 UTC, nguyenminhchien commented on account_credit_control/wizard/credit_control_policy_changer_view.xml
> +        id="action_wizard_credit_policy_changer_menu_action"
It opens tree view now, you only need to add  `<field name="view_mode">form</field>`

2023-03-30 03:45 UTC, nguyenminhchien commented on account_credit_control/wizard/credit_control_policy_changer_view.xml
> +    <record id="action_wizard_credit_policy_changer" model="ir.actions.act_window">
You should add a new menu to call this action, or delete it.

2023-03-30 08:30 UTC, astirpe commented
@nguyenminhchien regarding the two points left, I understand your proposal but I'm not yet fully convinced I want to change that part of code. Maybe the authors of that part could join the discussion, but for the time being I would leave it as it is, since this PR was meant to be a pure module migration. Do you mind to let the discussion continue on a separate PR once this one is merged?

2023-03-31 02:26 UTC, nguyenminhchien approved these changes
@astirpe: it's ok

2023-04-10 19:31 UTC, GabbasovDinar approved these changes
Code LGTM

2023-04-20 06:06 UTC, victoralmau commented
Please, cherry-pick https://github.com/OCA/credit-control/pull/279 to commit history

2023-04-20 07:24 UTC, astirpe commented
@victoralmau

- your migration scripts are for V15, so no need to include them in this PR
- the changes in the mail template were already implemented in February within this PR, so your PR seems to me a backport from this PR. Anyway I don't see anything to be cherry picked from https://github.com/OCA/credit-control/pull/279

2023-05-03 06:39 UTC, Bearnard21 requested changes
Credit control policy level form check
1. A check is performed after all policy levels were added to the credit control policy form. In case you've missed the custom mail message field in any of the credit control policy levels, you will get a warning on saving the whole policy. If there are several levels that were added, it's pretty inconvenient to check all the policy levels to find the missing field, so it would be nice if a check will be performed right on the policy level form.
2. In case you've chosen phone call action, you still have to fill mandatory e-mail template field.
3. If you're making changes in created policy level (eg. changing the channel from phone to e-mail), checking on the custom mail message field is not performed.

2023-05-08 11:06 UTC, astirpe commented
@Bearnard21 I see.

Point 1 and 3 are something related to a common issue of HTML fields, so I don't think there's a quick way to fix it within this PR. I found an old discussion where this issue is explained more in details: https://www.odoo.com/forum/help-1/how-to-make-a-html-field-mandatory-in-the-form-161104

For point 2 I agree that it's something should be fixed, but is a problem already existing in previous versions of this module, so I think it's better to open a dedicated issue for that. What do you think?

2023-05-22 05:09 UTC, Bearnard21 commented
Sorry for replying late,
Points 1 and 3
You can override the "New" method and recall function that sets up constrain for HTML to perform a check of the new policy right on a form view. Just keep in mind that the empty HTML field contains 12 symbols. 
Talking about point 2
Asking me, I think that improvement could be done in this PR.

2023-05-22 06:57 UTC, astirpe commented
@Bearnard21 please go ahead and open a PR to fix your points on previous versions. I will cherry pick your fixes to include them in this PR. Thanks!

2023-05-23 13:09 UTC, Bearnard21 approved these changes
Changes requested to be commited in next PR

2023-05-29 09:59 UTC, andreampiovesana commented
merge?

2023-05-29 12:05 UTC, pedrobaeza commented
/ocabot migration account_credit_control
/ocabot merge nobump

2023-05-29 12:11 UTC, merged

2023-06-02 15:30 UTC, grindtildeath commented on account_credit_control/models/credit_control_run.py
> +        action = action.read()[0]
This will raise `AccessError` for anyone not member of Settings/Administration group. Proper way to do it is:
```
action_name = "account_credit_control.credit_control_line_action"
action = self.env["ir.actions.act_window"]._for_xml_id(action_name)
```
That seems to be missing in the migration guide actually :confused:

2023-06-05 07:36 UTC, astirpe commented on account_credit_control/models/credit_control_run.py
> +        action = action.read()[0]
Thank you! I opened https://github.com/OCA/credit-control/pull/287