17.0 mig sale financial risk
OCA/credit-control pull request #377
Opened 2024-05-02 10:12 UTC by sbiosca-s73

Migrate sale_financial_risk module to version 17.0

2024-05-02 10:30 UTC, pedrobaeza commented
https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

/ocabot migration sale_financial_risk

2024-05-02 10:33 UTC, carlosdauden requested changes

2024-05-02 10:33 UTC, carlosdauden commented on sale_financial_risk/models/res_partner.py
> +            orderby="risk_partner_id, company_id",
Why you need order by that fields?
For better performance use _read_group to avoid order.

2024-05-02 10:33 UTC, carlosdauden commented on sale_financial_risk/models/sale.py
> +                                ),
You can replance by:
"origin_reference": f"{order._name},{order.id}",

2024-05-02 11:24 UTC, sbiosca-s73 commented
@carlosdauden changes done

2024-05-02 11:41 UTC, carlosdauden requested changes

2024-05-02 11:41 UTC, carlosdauden commented on sale_financial_risk/models/res_partner.py
> +            )
Try this:

```suggestion
        orders_group = self.env["sale.order.line"]._read_group(
            domain=self._get_risk_sale_order_domain(),
            groupby=["risk_partner_id", "company_id"],
            aggregates=["risk_amount:sum"],
        )
        for partner. company, risk_amount in orders_group:
            company_currency = company.currency_id
            partner.risk_sale_order = company_currency._convert(
                risk_amount,
                partner.risk_currency_id,
                company,
                fields.Date.context_today(self),
                round=False,
            )
```

2024-05-02 13:58 UTC, sbiosca-s73 commented
@carlosdauden changes done

2024-05-02 14:06 UTC, sbiosca-s73 commented
Not working test-requirements because the version of module account_financial_risk isn't correctly [version](https://github.com/OCA/credit-control/pull/347/files#diff-663023aec82d18b9e90463b1db577c8fef26638b6b60db1d62498dc4f55f34c5R7)

2024-05-02 14:27 UTC, carlosdauden approved these changes
Code LGTM

2024-05-27 15:11 UTC, ioans73 approved these changes

2024-06-17 21:35 UTC, Danisan commented
@pedrobaeza good work!

2024-06-18 06:09 UTC, pedrobaeza commented
You have to give thanks to the contributors doing the migration and the review.

@sbiosca-s73 please split the pre-commit changes from the migration itself as stated in the migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

2024-06-18 06:39 UTC, sbiosca-s73 commented
@pedrobaeza changes done. Thanks!

2024-06-18 06:43 UTC, pedrobaeza commented
/ocabot merge nobump

2024-06-18 07:50 UTC, merged