[16.0][FIX] account_credit_control: replace final due amount by balanced amount
OCA/credit-control pull request #380
Opened 2024-05-23 11:39 UTC by StephaneMangin

As an invoice can be partiel, the total due amount should reflect this state.
Changing the report final amounts by correct ones in the communication.

2024-05-23 11:57 UTC, cyrilmanuel approved these changes

2024-05-23 12:05 UTC, leemannd requested changes
You're changing the behavior of the module. It can be a valid change, but if you're doing so please update also the headers of the table to reflect this change:
- https://github.com/OCA/credit-control/pull/380/files#diff-ab2ca28045e4ca81ddb0cacf900797263a04da3c88c8f3f46b93ebeca3b2d9bbL184
-  https://github.com/OCA/credit-control/pull/380/files#diff-ab2ca28045e4ca81ddb0cacf900797263a04da3c88c8f3f46b93ebeca3b2d9bbL185

2024-05-23 12:10 UTC, StephaneMangin commented
> You're changing the behavior of the module. It can be a valid change, but if you're doing so please update also the headers of the table to reflect this change:
> 
> * https://github.com/OCA/credit-control/pull/380/files#diff-ab2ca28045e4ca81ddb0cacf900797263a04da3c88c8f3f46b93ebeca3b2d9bbL184
> * https://github.com/OCA/credit-control/pull/380/files#diff-ab2ca28045e4ca81ddb0cacf900797263a04da3c88c8f3f46b93ebeca3b2d9bbL185

It is the same concept, invoice total and balanced total (actual amount due)

2024-05-23 13:50 UTC, imlopes approved these changes
LGTM

2024-05-23 13:52 UTC, pedrobaeza requested changes
The invoice total shouldn't be changed. It's reflecting the total of the invoice, no matter the amount due, and I don't understand the other change. Why `amount_due` is not valid and you are putting `balance_due`?

2024-05-27 13:25 UTC, StephaneMangin commented
> The invoice total shouldn't be changed. It's reflecting the total of the invoice, no matter the amount due, and I don't understand the other change. Why `amount_due` is not valid and you are putting `balance_due`?

Hi Pedro, in fact `amount_due` is the invoice total amount (`amount_currency`) and `balance_due` is the real actual due amount in the context of a partial invoice (amount_residual_currency).

When amount_due was used in the summary, it was wrong with a residual due amount.

Or i'm wrong understanding this implementation. Let me know

2024-05-27 16:17 UTC, pedrobaeza commented
The total of the invoice should be reflected. Example: Invoice: 1000 €. Due: 500 €. I don't know the difference between `amount_due` and `balance_due` though.

2024-05-28 08:07 UTC, StephaneMangin commented
> 1000 €. Due: 500 €. I don't know the difference between `amount_due` and `balance_due` though.

I just explained this difference in my previous com. Maybe not so clearly though.

As i can see it right now and after a client bugfix: 
 - amount due is the invoice/move line total
 - balance_due is the residual amount for a partial invoice

When i use these two fields in the summary values are valid and reflect what to pay.

2024-11-03 12:14 UTC, closed without merging