[MIG] partner_payment_return_risk > account_payment_return_financial_risk: Migration to 11.0
OCA/credit-control pull request #4
Opened 2018-05-09 10:13 UTC by carlosdauden

@Tecnativa

2018-05-14 17:29 UTC, pedrobaeza requested changes
You have to rename all the occurrences of `partner_payment_return_risk` to `account_payment_return_financial_risk` on translation files.

2018-05-14 17:29 UTC, pedrobaeza commented on oca_dependencies.txt
> +https://github.com/tecnativa/credit-control/tree/11.0-mig-partner_financial_risk
To be removed before merging

2018-06-21 07:10 UTC, pedrobaeza commented
@carlosdauden tests are not adjusted for v11. Please fix that

2018-06-21 07:57 UTC, cubells requested changes

2018-06-21 07:57 UTC, cubells commented on account_payment_return_financial_risk/tests/test_payment_return_risk.py
> +        cls.invoice.signal_workflow('invoice_open')
You must change `cls.invoice.signal_workflow('invoice_open')` by `cls.invoice.action_invoice_open()`

2018-06-21 16:42 UTC, carlosdauden commented
@cubells All green now

2018-06-21 16:52 UTC, pedrobaeza approved these changes

2018-06-21 16:52 UTC, pedrobaeza commented
Merging as @cubells's comments have been honored.

2018-06-21 16:53 UTC, merged

2018-06-22 08:16 UTC, cubells commented
thanks @carlosdauden