[WIP][MIG][13.0] account_financial_risk: Migration to v13.0
OCA/credit-control pull request #52
Opened 2020-02-08 09:13 UTC by sergio-teruel

TT21602

2020-02-10 12:17 UTC, carlosdauden requested changes

2020-02-10 12:17 UTC, carlosdauden commented on account_financial_risk/models/res_partner.py
> +        for _key, group in groups.items():
```suggestion
        for group in groups.values():
```

2020-02-10 15:23 UTC, sergio-teruel commented
@carlosdauden Changes done

2020-02-15 14:25 UTC, alan196 approved these changes
👍 Functional and Technical Review

2020-02-28 16:29 UTC, alan196 commented
I have an issue when I try to open a partner that is not a customer.

`res.partner(23),risk_exception`

I have created the following PR to fix this https://github.com/Tecnativa/credit-control/pull/4

2020-02-28 16:30 UTC, alan196 requested changes
Add changes of PR https://github.com/Tecnativa/credit-control/pull/4

2020-02-28 19:08 UTC, pedrobaeza commented
I have added the PR but Travis is red now. I agree on not classifying by `customer_rank` (show for all), but if you think it shouldn't be shown only for partners with rank, please modify it. @carlosdauden what is your opinion on this?

2020-04-20 09:05 UTC, gdgellatly approved these changes
Static Review, 1 very minor nitpick. I don't even care about it and I could be wrong for all I know. The only other comment is the invoice_unpaid_margin title in settings is not great English, but seeing it was ported and I imagine translations etc rely on it, it wasn't bad enough to make a fuss over.

2020-04-20 09:05 UTC, gdgellatly commented on account_financial_risk/models/res_company.py
> +            vals = vals.copy()
Nitpick, is `copy` really needed here?

2020-06-09 16:39 UTC, pedrobaeza commented
Closing in favor of #67

2020-06-09 16:39 UTC, closed without merging

2020-06-09 16:39 UTC, carlosdauden commented
Cose this PR in favour of https://github.com/OCA/credit-control/pull/67